### ISSUE TITLE
CADE O README?

### ISSUE THREAD

**Issue by leandrofahur** [tatacsd/CSIS3375-UX-Design-in-Mobile-Apps#3]
Cade o README?

**Comment by leandrofahur** [comment]
Nao use emojis pra que fique bem profissional!

**Comment by leandrofahur** [comment]
Na verdade, copia e cola um meu e mudas as palavras!

**Comment by leandrofahur** [comment]
@tatacsd estarei acompanhando... 🥸

**Comment by tatacsd** [comment]
> Cade o README?

Working on it, sir.
